/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export interface HealthResponse200 {
    healthy: boolean
}

export const HealthResponse200 = {
    validate: (await import('./schemas/health-response200.schema.js'))
        .validate10 as unknown as ValidateFunction<HealthResponse200>,
    get schema() {
        return HealthResponse200.validate.schema
    },
    get errors() {
        return HealthResponse200.validate.errors ?? undefined
    },
    is: (o: unknown): o is HealthResponse200 => HealthResponse200.validate(o) === true,
    assert: (o: unknown) => {
        if (!HealthResponse200.validate(o)) {
            throw new AjvValidator.ValidationError(HealthResponse200.errors ?? [])
        }
    },
} as const
